### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by CaptainAke** [KurangKering/n3w_5t135#2]
1. input di pemasukan lain saldo nya gak ada inpunya.
2. pengeluaran lain ngikut pemasukan lain
3. Menu laporan ketuanya dananya pisah2.
- Laporan Uang Pendaftaran (total aja)
- Laporan Uang Semester & Pembangunan (total aja) 
- Laporan Operasional.(pemasukan lainnya,gaji & pengeluaran)  (pemasukan,pengeluaran dan total)

**Comment by KurangKering** [comment]
apa ni banyak

**Comment by CaptainAke** [comment]
Kalo bisa kasih menu diagram ^^

**Comment by KurangKering** [comment]
point 1 sama dua tu apa maksudnya ? terus point 3 tu apa ?

**Comment by CaptainAke** [comment]
*Di menu form input pemasukan untuk saldonya gk ada d aku
*di menu pengeluaran lain itu kyk menu pemasukan lain. Ada nmbah sldo awal, saldo terpakai sama total saldo sekarang
*rombak jd 3 menu di laporan ketua. Tampilannyakn dh ku kirim d WA docx .
